import type { Template } from '../../types/template.js';

export const BUILT_IN_TEMPLATES: Template[] = [
  {
    name: 'postgres',
    description: 'PostgreSQL database server',
    version: '1.0.0',
    tags: ['database', 'sql', 'postgres'],
    image: 'postgres:15-alpine',
    ports: [{ host: 5432, container: 5432, protocol: 'tcp' }],
    environment: {
      POSTGRES_PASSWORD: '${DB_PASSWORD}',
      POSTGRES_DB: '${DB_NAME}',
      POSTGRES_USER: '${DB_USER}',
    },
    volumes: [{ source: 'pgdata', target: '/var/lib/postgresql/data' }],
    restart: 'unless-stopped',
    healthcheck: {
      test: ['CMD-SHELL', 'pg_isready -U postgres'],
      interval: '10s',
      timeout: '5s',
      retries: 5,
    },
    variables: [
      { name: 'DB_PASSWORD', description: 'Database password', required: true, type: 'password' },
      { name: 'DB_NAME', description: 'Database name', default: 'postgres', type: 'string' },
      { name: 'DB_USER', description: 'Database user', default: 'postgres', type: 'string' },
    ],
  },
  {
    name: 'mysql',
    description: 'MySQL database server',
    version: '1.0.0',
    tags: ['database', 'sql', 'mysql'],
    image: 'mysql:8',
    ports: [{ host: 3306, container: 3306, protocol: 'tcp' }],
    environment: {
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}',
      MYSQL_DATABASE: '${MYSQL_DATABASE}',
      MYSQL_USER: '${MYSQL_USER}',
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}',
    },
    volumes: [{ source: 'mysql-data', target: '/var/lib/mysql' }],
    restart: 'unless-stopped',
    variables: [
      { name: 'MYSQL_ROOT_PASSWORD', description: 'Root password', required: true, type: 'password' },
      { name: 'MYSQL_DATABASE', description: 'Database name', default: 'myapp', type: 'string' },
      { name: 'MYSQL_USER', description: 'Application user', default: 'user', type: 'string' },
      { name: 'MYSQL_PASSWORD', description: 'User password', required: true, type: 'password' },
    ],
  },
  {
    name: 'mongodb',
    description: 'MongoDB document database',
    version: '1.0.0',
    tags: ['database', 'nosql', 'mongodb'],
    image: 'mongo:6',
    ports: [{ host: 27017, container: 27017, protocol: 'tcp' }],
    environment: {
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}',
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}',
    },
    volumes: [{ source: 'mongo-data', target: '/data/db' }],
    restart: 'unless-stopped',
    variables: [
      { name: 'MONGO_USER', description: 'Root username', default: 'admin', type: 'string' },
      { name: 'MONGO_PASSWORD', description: 'Root password', required: true, type: 'password' },
    ],
  },
  {
    name: 'redis',
    description: 'Redis in-memory data store',
    version: '1.0.0',
    tags: ['cache', 'database', 'redis'],
    image: 'redis:7-alpine',
    ports: [{ host: 6379, container: 6379, protocol: 'tcp' }],
    volumes: [{ source: 'redis-data', target: '/data' }],
    command: ['redis-server', '--appendonly', 'yes'],
    restart: 'unless-stopped',
    healthcheck: { test: ['CMD', 'redis-cli', 'ping'], interval: '10s', timeout: '5s', retries: 3 },
  },
  {
    name: 'nginx',
    description: 'Nginx web server',
    version: '1.0.0',
    tags: ['web', 'proxy', 'nginx'],
    image: 'nginx:alpine',
    ports: [
      { host: 80, container: 80, protocol: 'tcp' },
      { host: 443, container: 443, protocol: 'tcp' },
    ],
    restart: 'unless-stopped',
  },
  {
    name: 'rabbitmq',
    description: 'RabbitMQ message broker with management UI',
    version: '1.0.0',
    tags: ['queue', 'messaging', 'rabbitmq'],
    image: 'rabbitmq:3-management-alpine',
    ports: [
      { host: 5672, container: 5672, protocol: 'tcp' },
      { host: 15672, container: 15672, protocol: 'tcp' },
    ],
    environment: {
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}',
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}',
    },
    volumes: [{ source: 'rabbitmq-data', target: '/var/lib/rabbitmq' }],
    restart: 'unless-stopped',
    variables: [
      { name: 'RABBITMQ_USER', description: 'RabbitMQ username', default: 'admin', type: 'string' },
      { name: 'RABBITMQ_PASSWORD', description: 'RabbitMQ password', required: true, type: 'password' },
    ],
  },
  {
    name: 'elasticsearch',
    description: 'Elasticsearch search engine',
    version: '1.0.0',
    tags: ['search', 'elasticsearch', 'database'],
    image: 'elasticsearch:8.11.0',
    ports: [
      { host: 9200, container: 9200, protocol: 'tcp' },
      { host: 9300, container: 9300, protocol: 'tcp' },
    ],
    environment: {
      'discovery.type': 'single-node',
      'xpack.security.enabled': 'false',
      ES_JAVA_OPTS: '-Xms512m -Xmx512m',
    },
    volumes: [{ source: 'es-data', target: '/usr/share/elasticsearch/data' }],
    restart: 'unless-stopped',
  },
  {
    name: 'minio',
    description: 'MinIO S3-compatible object storage',
    version: '1.0.0',
    tags: ['storage', 's3', 'minio'],
    image: 'minio/minio:latest',
    ports: [
      { host: 9000, container: 9000, protocol: 'tcp' },
      { host: 9001, container: 9001, protocol: 'tcp' },
    ],
    environment: {
      MINIO_ROOT_USER: '${MINIO_USER}',
      MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD}',
    },
    volumes: [{ source: 'minio-data', target: '/data' }],
    command: ['server', '/data', '--console-address', ':9001'],
    restart: 'unless-stopped',
    variables: [
      { name: 'MINIO_USER', description: 'MinIO root user', default: 'minioadmin', type: 'string' },
      { name: 'MINIO_PASSWORD', description: 'MinIO root password (min 8 chars)', required: true, type: 'password' },
    ],
  },
  {
    name: 'mailhog',
    description: 'Email testing tool for developers',
    version: '1.0.0',
    tags: ['email', 'testing', 'development'],
    image: 'mailhog/mailhog:latest',
    ports: [
      { host: 1025, container: 1025, protocol: 'tcp' },
      { host: 8025, container: 8025, protocol: 'tcp' },
    ],
    restart: 'unless-stopped',
  },
];
